# Generated by Django 4.2.13 on 2024-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
