# Generated by Django 5.0.6 on 2024-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('no_of_people', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
