# Generated by Django 5.0.6 on 2024-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('time_log', models.TimeField(help_text='enter the exact time')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'Civil'), ('2', 'Electrical'), ('3', 'Mechanical'), ('4', 'CompSci')], default='1', max_length=20)),
            ],
        ),
    ]
