# Generated by Django 5.0.6 on 2024-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('shift', models.IntegerField(max_length=50)),
            ],
        ),
    ]
