# Generated by Django 5.0.6 on 2024-05-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='food_name',
        ),
    ]
