# Generated by Django 5.0.6 on 2024-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_name_menu_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
